### ISSUE TITLE
AttributeError: module 'toga' has no attribute 'App'

### ISSUE THREAD

**Issue by Barbosabyte** [pybee/toga-demo#11]
Followed the tutorial on RTD, but I get this error running toga-demo:
AttributeError: module 'toga' has no attribute 'App'
Needless to say that if I try the first example it returns the same error.

**Comment by freakboy3742** [comment]
What platform are you running on? (macOS? iOS? Linux?) If you're running Windows, you've probably fallen foul of #4.

**Comment by Barbosabyte** [comment]
I'm on Linux (Xubuntu 16.04 64 bit). I made sure to use pip3 and I tried running inside and outside a virtual environment. 
This is the full output:
```
Traceback (most recent call last):
  File "/usr/local/bin/toga-demo", line 7, in <module>
    from toga_demo.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/toga_demo/__main__.py", line 6, in <module>
    from .app import TogaDemo
  File "/usr/local/lib/python3.5/dist-packages/toga_demo/app.py", line 8, in <module>
    class TogaDemo(toga.App):
AttributeError: module 'toga' has no attribute 'App'
```

**Comment by Barbosabyte** [comment]
It was a problem with toga installation. I used `sudo pip3 install toga-demo -I` and now it works.
